apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-02-serviceaccount
  namespace: manufacturing-mas
  labels:
    app: manufacturing-mas
    agent: agent-02
automountServiceAccountToken: false
